FROM ros:foxy-ros-base

RUN apt-get update && apt-get upgrade -y \
        && apt-get install -y nano \
        && apt-get install -y ros-foxy-rqt-image-view \
        && apt-get install -y ros-foxy-compressed-image-transport \
        && apt-get install -y python3-opencv \
        && apt-get install -y qt5-default \
	&& useradd -ms /bin/bash user \
	&& echo "user:user" | chpasswd && adduser user sudo \
	&& echo "user ALL=(ALL) NOPASSWD: ALL " >> /etc/sudoers

USER user
WORKDIR /home/user
RUN sudo usermod -a -G video user

RUN mkdir -p /home/user/dev_ws/src

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F42ED6FBAB17C654
RUN git clone https://github.com/Unity-Technologies/ROS-TCP-Endpoint /home/user/dev_ws/src/ros_tcp_endpoint -b ROS2v0.7.0

COPY ./Scripts/ /home/user/dev_ws/scripts/
RUN sudo chmod +x /home/user/dev_ws/scripts/*

COPY ./source_ros.sh /home/user/dev_ws/source_ros.sh

RUN echo "cd /home/user/dev_ws" >> ~/.bashrc

RUN cd /home/user/dev_ws && . /opt/ros/foxy/setup.sh && colcon build

RUN sudo chown -R user /home/user/dev_ws

RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
RUN echo ". install/local_setup.bash" >> ~/.bashrc
